### ISSUE TITLE
Certificate Issuance

### ISSUE THREAD

**Issue by lookuptable** [istio/auth#1]
Istio auth needs a component for certificate issuance. Basic functionalities should include:
- If a signing key & certificate are provided (via command line), use them as CA root key and cert. Otherwise, generate a key & certificate automatically
- Has an interface to create key & certificate when provided with a Kubernetes service account (name + namespace)

**Comment by wlu2016** [comment]
https://github.com/istio/auth/commit/7b6ce24c1bf0eb9f663004d1babee11796ec6ee5
