### ISSUE TITLE
Create e2e for istio-ca

### ISSUE THREAD

**Issue by lookuptable** [istio/auth#115]
We should add basic e2e tests for istio-ca. The tests should cover
- [x] When deployed to a Kubernetes cluster, secrets are correctly created for existing service account
- [x] Creating a new service account leads to the creation of corresponding secret
- [x] Cert in created secret can be successfully verified
- [ ] Istio-ca re-creates secret when one is deleted.

**Comment by sebastienvas** [comment]
Are you thinking of Adding this in istio/istio e2e framework ?

**Comment by wattli** [comment]
For item 1, more specifically, secrets should be overwritten if they already exist

**Comment by lookuptable** [comment]
@sebastienvas I'm thinking of adding it here as part of presubmit. Currently the CA command line stuff is not tested.

**Comment by sebastienvas** [comment]
Awesome

**Comment by wattli** [comment]
@lookuptable , is this issue finished?

**Comment by lookuptable** [comment]
Nope. Hasn't get a chance to work on this.
