### ISSUE TITLE
Auth support for TCP

### ISSUE THREAD

**Issue by wattli** [istio/auth#151]

**Comment by wattli** [comment]
Problem summary https://docs.google.com/document/d/1-R9muDf78bA-f5WcxXtnZ_noFFR4MLb00xI2djGS0Ps/edit

**Comment by ldemailly** [comment]
How would this work for https (without double encrypting all the traffic) ?

**Comment by lizan** [comment]
@ldemailly No, the key issue is missing LDS, for HTTP we can route traffic to different services by inspecting host header, but for TCP it needs LDS to know which service that app is talking to. The underlying encryption happen at same level. See the docs for details.

**Comment by wattli** [comment]
@kyessenov , just to confirm: this is done, right?

**Comment by kyessenov** [comment]
LDS is implemented and supports TCP clusters, if that's the question.

**Comment by wattli** [comment]
Yes, thanks.

**Comment by wattli** [comment]
@kyessenov , so the secure naming in CDS for TCP also works, right?

**Comment by kyessenov** [comment]
I think so. We have no negative tests for auth, so this remains to be verified.

**Comment by wattli** [comment]
i see, i will take care of that.

**Comment by ldemailly** [comment]
I fixed it in https://github.com/istio/istio/pull/711 and I'm starting to write a negative test but if you want to do it I can do something else
