### ISSUE TITLE
Istio auth support on v0.2

### ISSUE THREAD

**Issue by wattli** [istio/auth#153]

**Comment by odeke-em** [comment]
Dup of https://github.com/istio/auth/issues/152?

**Comment by wattli** [comment]
Design doc: https://docs.google.com/document/d/1VYjmL72aszfkSGB5wyDRUQf4EMibW5UP38RA8KBwB-o/edit#heading=h.p6i3oklcxw0

**Comment by wattli** [comment]
@odeke-em, this is the epic, the other one is the issue.

**Comment by sakshigoel12** [comment]
We have 3 open P0 under this epic. Please could you close all issues that are complete - and call out anything that won't be complete by EOW (except docs and testing).
