### ISSUE TITLE
Make sure node agent cert rotation work

### ISSUE THREAD

**Issue by myidpt** [istio/auth#220]
Places to improve:

If CSR failed, we should retry
Generally the rotation should happen before the cert expires, the common practice is half time of the cert life, iirc.

**Comment by lookuptable** [comment]
Node agent is already handling rotation. See code [here](https://github.com/istio/auth/blob/master/node_agent/na/nodeagent.go#L100). Can you specify what else you're planning on doing?

**Comment by wattli** [comment]
That one has bug, i mean we should improve it. The title is changed. 

Places to improve:
- If CSR failed, we should retry
- Generally the rotation should happen before the cert expires, the common practice is half time of the cert life, iirc.

**Comment by lookuptable** [comment]
Sounds good to me. Thanks for the explanation.

**Comment by myidpt** [comment]
OK. Thanks for the explanation.

**Comment by myidpt** [comment]
This is fixed by PR #220.
