### ISSUE TITLE
Transparent mutual TLS auth setup conflicts with kubernetes health probes

### ISSUE THREAD

**Issue by wattli** [istio/auth#262]

**Comment by wattli** [comment]
This issue was originally raised by Kuat at (https://github.com/istio/pilot/issues/479) and here is the context.
------
In case of mutual TLS enabled mesh, the health checker in k8s does not have a client-side proxy to initiate the TLS connection. That means the health probes initiated by kubelet will be sent as clear text to the proxy that expect an SSL connection.

Concretely, let's say my pod declared port 80, that is used by service port 80. I add a liveness probe on port 80, path /status. Proxy creates a TLS context on port 80. Kubelet makes a request to port 80 path /status. Request doesn't go through the proxy since proxy expects SSL. Kubelet kills the pod.

**Comment by ldemailly** [comment]
can the healthcheck be using socat/same mechanism as kubectl port-forward which bypasses the proxy already ? (there is maybe an option to set it up that way)

**Comment by wattli** [comment]
It's a dup of https://github.com/istio/auth/issues/292, closed.
