### ISSUE TITLE
Refactor node_agent

### ISSUE THREAD

**Issue by myidpt** [istio/auth#308]
We should move most files from cmd/node_agent/na/ to pkg/. This aligns with the general structure of the auth repo.

**Comment by crazytan** [comment]
I tried to do this in a naive way, but hit some circular dependency error because to implement `GetDialOptions` depends on `package na`, whose function `NewNodeAgent` in turn depends on `gcpPlatformImpl`.

**Comment by myidpt** [comment]
Yes, it is. I have done a little work to separate the Config. I will send out a PR on this, and you can continue to do more refactoring, if you don't mind ;)
