### ISSUE TITLE
Istio auth e2e with manager/mixer/manager agent/proxy 

### ISSUE THREAD

**Issue by myidpt** [istio/auth#47]

**Comment by rshriram** [comment]
It would be nice to have this integrated into the bookinfo demo application. It has enough complexity to exercise all aspects of the system.

**Comment by rshriram** [comment]
Demo app is in istio/istio/demos/apps/bookinfo

**Comment by lookuptable** [comment]
Sounds good @rshriram 

We are still working on a few blockers. Once they are resolved I'm happy to integrate auth into the bookinfo demo.

**Comment by lookuptable** [comment]
Create istio/istio#82 to track this.
