### ISSUE TITLE
Investigate how Envoy handles the rotation of SSL keys and certs

### ISSUE THREAD

**Issue by wattli** [istio/auth#50]
When we rotate key/cert, we have 2 options 1) keep the same name 2) use a different name.

The first option is simpler since we don't need to update envoy config in this case. But it may have problems:

If envoy directly reads cert/key from file every time when they need them, then we are fine. However, if they keep the cert/key in memory or use some cache, the new key/cert with the same file name will not be able to populate. In that case, we need to go with the second option.

I am investigating on this.

**Comment by lookuptable** [comment]
I think the best approach is to change Envoy such that it keeps tracks of the cert timestamp and reload cert/key when necessary.

Renaming means every time we rotate key/cert, the Envoy config needs to be re-generated, which makes the CA and manager tightly coupled.

**Comment by wattli** [comment]
It would be optional, i.e., envoy has a watcher for key/cert, and reload when necessary. AFAIK, I don't think envoy has this feature. Maybe we can bring up the e2e demo first, and then try it ourselves. And in the meantime, i can look into envoy code to get more info.

**Comment by wattli** [comment]
Btw, this is not a show blocker. P2.

**Comment by myidpt** [comment]
I think option 1 is feasible. It is rationale for Envoy to check the timestamp in the cert when using it, and refreshes it when it's expired. I agree this is P2, as long as both client and server do not check timestamps. If current code checks timestamps, we may need to consider this as blocking issue.

**Comment by lookuptable** [comment]
It's not blocking out first E2E demo/test but it is an ALPHA blocker. Since in alpha we'll use short-lived certs.

**Comment by wattli** [comment]
Since it is blocking alpha, bump it up to p1

**Comment by wattli** [comment]
Some response from Matt:
----
It's possible to support reload of certs directly, but I would rather just add the LDS API which will allow hot swap of entire listeners. This is a more general solution which helps a lot of other uses cases. For now, I would just hot restart Envoy if you need to change the cert for the listener. LDS is going to get implemented in the next 1-2 months.
---

Note: I just added this feature request (dynamically load cert) to the tracking bug at envoy: lyft/envoy#315

**Comment by wlu2016** [comment]
per discussion, we will provide a short-term fix by adding a listener on Istio manager to watch key&cert change and restart Envoy if necessary. 

We will create a separate issue to track the long-term fix to support refreshing new key/cert dynamically, like adding the LDS API which will allow hot swap of entire listeners as Matt suggested here.

**Comment by lookuptable** [comment]
The short-term solution (istio/manager#663) is merged. 

Long-term solution is tracked by #95 where Envoy provides native support to reload key/cert without restarting the proxy.
