### ISSUE TITLE
Handle key/certificate rotations

### ISSUE THREAD

**Issue by lookuptable** [istio/auth#56]

**Comment by wattli** [comment]
------- Response from Matt: --------
"_It's possible to support reload of certs directly, but I would rather just add the LDS API which will allow hot swap of entire listeners. This is a more general solution which helps a lot of other uses cases. For now, I would just hot restart Envoy if you need to change the cert for the listener. LDS is going to get implemented in the next 1-2 months._" 
-------

Just added this feature request (dynamically load cert) to the tracking bug at envoy: https://github.com/lyft/envoy/issues/315
