### ISSUE TITLE
Investigate on the deployment flow 

### ISSUE THREAD

**Issue by wattli** [istio/auth#57]
There are basically 3 scenarios in the deployment of Istio Auth:

1) There are no apps/proxies, we want to deploy apps and proxies (with Auth enabled).

2) Apps running without proxies, we want to deploy proxies (with Auth enabled)

3) Apps running with proxies (but without Auth enabled), we want to deploy proxies (with Auth enabled)

Need to investiagation the deployment flow of each of the scenario.

**Comment by wattli** [comment]
After chatting with @kyessenov and @andraxylia, here are some ideas.

For scenario 1, this is the easiest one, we need to deploy Istio CA/Mixer/Manager/Manager Agent/Proxy (auth enabled)/App just similar to https://github.com/istio/istio/tree/master/demos

For scenario 2, currently Istio deployment flow is to restart the pod since k8s can't add containers to a running pod (confirmed with Kuat and Andra). So we also need to restart app, and bring up other parts in the meantime.

For scenario 3, we need to update the manager agent yml file, which means at least we need to restart proxies with the auth config, and we need to bring up Istio CA (if it is not running). We may not need to bring up Mixer/Manager. We can definitely try when the e2e is ready.

**Comment by wattli** [comment]
For scenario 3, we need to restart Manager Agent as well since we need to update its config (to enable auth)

**Comment by myidpt** [comment]
About the deployment order: The CA should be up before enabling auth on proxies. In case auth is enabled and the private key/cert chain files are not available locally (may because CA is not up), we should fail the start of proxy. More intelligent way is to do retry, but I think that's second priority :)

**Comment by wattli** [comment]
Good point, maybe we fail the proxy start process and prompt some error message 'key/cert not available, check if Istio CA is up and then retry'.

**Comment by lookuptable** [comment]
Pretty sure we'll get this for free from Kubernetes - Kubernetes will retry pod creation until the secret to be mounted becomes existent.

**Comment by wattli** [comment]
This is done.
