### ISSUE TITLE
Differentiate "allow-all" and "allow-none" in ssl_context:verify_subject_alt_name

### ISSUE THREAD

**Issue by myidpt** [istio/auth#66]
"allow-all": No secure naming is checked.
"all-none": Secure naming is checked against an empty list of service accounts. So it always fails.

We need to verify whether Envoy supports the two cases through config. Ideally, an undefined verify_subject_alt_name field should mean "allow-all" and a defined but empty verify_subject_alt_name field should mean "allow-none".

**Comment by lookuptable** [comment]
This should be addressed by lyft/envoy#615

**Comment by lookuptable** [comment]
lyft/envoy#648 fixes this issue in Envoy upstream

**Comment by PiotrSikora** [comment]
Please note that https://github.com/lyft/envoy/issues/648 was reverted in Envoy (see: https://github.com/lyft/envoy/issues/615, https://github.com/lyft/envoy/pull/668).

**Comment by wattli** [comment]
@lookuptable , is this issue solved? I think currently we enforce client cert now.
