### ISSUE TITLE
Move presubmit to Jenkins

### ISSUE THREAD

**Issue by yutongz** [istio/auth#76]
Manager, proxy and other repos even the postsubmit of auth use Jenkins, it would be nice if we can move presubmit of auth into Jenkins. It makes sharing scripts and tools more easily.

**Comment by yutongz** [comment]
I am working on this issue

**Comment by lookuptable** [comment]
Thanks for volunteering!

**Comment by yutongz** [comment]
Fixed with https://github.com/istio/auth/pull/77
